# Generated by Django 5.2.3 on 2025-06-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_commandeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeitem',
            name='couleur',
            field=models.CharField(default='noir', max_length=20),
        ),
        migrations.AddField(
            model_name='commandeitem',
            name='taille',
            field=models.CharField(default='M', max_length=5),
        ),
    ]
